IBC hooks and Token Factory
KendrickAng/feather-core pull request #7
Opened 2023-05-09 10:50 UTC by emidev98

This pull request integrate: 
- [ibc-hooks](https://github.com/terra-money/core/tree/main/x/ibc-hooks) the same way as in Terra Core,
- [token-factory](https://github.com/osmosis-labs/osmosis/tree/main/x/tokenfactory) as a native module.

2023-05-11 05:55 UTC, javiersuweijie approved these changes

2023-05-12 03:25 UTC, KendrickAng commented on app/params/proto.go
> +func MakeEncodingConfig() EncodingConfig {
please use the existing `MakeEncodingConfig()` in `app/encoding.go` so we can avoid code duplication

2023-05-12 06:55 UTC, KendrickAng commented on start.sh
please run a `chmod +x start.sh` and re-commit the file - otherwise the file will be cloned without the execute bit set. [Reference](https://stackoverflow.com/questions/39666585/does-git-store-the-read-write-execute-permissions-for-files)

2023-05-12 07:01 UTC, KendrickAng commented on start.sh
> +feather-cored init test
```suggestion
feather-cored init test --overwrite --chain-id test
```

2023-05-12 07:01 UTC, KendrickAng commented on start.sh
> +feather-cored keys add test --keyring-backend os
```suggestion
yes | feather-cored keys add test --keyring-backend os
```

2023-05-12 07:01 UTC, KendrickAng commented on start.sh
> +feather-cored keys add test --keyring-backend os
```suggestion
yes | feather-cored keys add test --keyring-backend os
```

2023-05-12 07:02 UTC, KendrickAng requested changes
There are some parts that I feel should be addressed - commented!

2023-05-12 07:03 UTC, KendrickAng approved these changes
LGTM 👍🏻

2023-05-12 07:03 UTC, merged